/* ================== LearnEn DATA ================== */
const LEVELS = [
  { code: "A1", name: "مبتدی", desc: "الفبا، سلام‌واحوال‌پرسی، جملات ساده", color: "linear-gradient(135deg,#22c55e,#06b6d4)" },
  { code: "A2", name: "مقدماتی", desc: "زمان‌های اصلی، توصیف روزمره", color: "linear-gradient(135deg,#06b6d4,#3b82f6)" },
  { code: "B1", name: "متوسط", desc: "زمان‌های کامل، جملات شرطی، مکالمه", color: "linear-gradient(135deg,#7c3aed,#3b82f6)" },
  { code: "B2", name: "بالاتر از متوسط", desc: "مجهول، نقل‌قول، عبارات پیشرفته", color: "linear-gradient(135deg,#f472b6,#7c3aed)" },
  { code: "C1", name: "پیشرفته", desc: "ساختارهای پیچیده، اصطلاحات، نگارش", color: "linear-gradient(135deg,#f59e0b,#ef4444)" },
];

/* --- Lessons --- */
const LESSONS = [
  {
    id: "a1-alphabet", level: "A1", title: "الفبا و تلفظ", en: "The Alphabet & Sounds",
    summary: "۲۶ حرف الفبای انگلیسی و صداهای اصلی آن‌ها",
    content: [
      { type: "p", text: "زبان انگلیسی ۲۶ حرف دارد: ۵ حرف صدادار (A, E, I, O, U) و ۲۱ حرف بی‌صدا. برخلاف فارسی، هر حرف ممکن است چند صدای متفاوت داشته باشد، پس یادگیری تلفظ همراه با واژه بسیار مهم است." },
      { type: "table", head: ["Letter", "Name", "Example"], rows: [["A a", "/eɪ/", "apple, cat, name"], ["B b", "/biː/", "book, baby"], ["C c", "/siː/", "cat, city"], ["E e", "/iː/", "egg, me"], ["G g", "/dʒiː/", "go, giant"], ["I i", "/aɪ/", "it, ice"], ["O o", "/oʊ/", "on, open"], ["U u", "/juː/", "up, use"], ["W w", "/ˈdʌbəl.juː/", "water"], ["Y y", "/waɪ/", "yes, happy"]] },
      { type: "rule", html: "حروف صدادار: <code>A E I O U</code> — گاهی <code>Y</code> هم نقش صدادار دارد (مثل happy)." },
      { type: "examples", items: [["Apple", "سیب"], ["Book", "کتاب"], ["Cat", "گربه"], ["Dog", "سگ"], ["Egg", "تخم‌مرغ"]] },
      { type: "tip", text: "هر روز ۵ دقیقه الفبا را با صدای بلند بخوانید. روی دکمهٔ 🔊 کنار هر مثال کلیک کنید تا تلفظ صحیح را بشنوید." },
    ],
    practice: [
      { q: "Which letter is a vowel?", opts: ["B", "E", "T", "K"], a: 1 },
      { q: "How many letters are in the English alphabet?", opts: ["24", "26", "28", "32"], a: 1 },
    ],
  },
  {
    id: "a1-greetings", level: "A1", title: "سلام و احوال‌پرسی", en: "Greetings & Introductions",
    summary: "چطور سلام کنیم، خودمان را معرفی کنیم و خداحافظی کنیم",
    content: [
      { type: "p", text: "اولین قدم در هر زبانی، سلام‌واحوال‌پرسی است. در انگلیسی بسته به رسمی یا غیررسمی بودن موقعیت، عبارات متفاوتی استفاده می‌شود." },
      { type: "table", head: ["Formal", "Informal", "فارسی"], rows: [["Good morning", "Morning!", "صبح بخیر"], ["Good afternoon", "Hi / Hey", "عصر بخیر / سلام"], ["How do you do?", "What's up?", "حال شما چطور است؟"], ["Goodbye", "Bye / See ya", "خداحافظ"], ["Nice to meet you", "Nice meeting you", "از آشنایی‌تان خوشوقتم"]] },
      { type: "examples", items: [["Hello! My name is Sara.", "سلام! اسم من ساراست."], ["Nice to meet you.", "از آشنایی با شما خوشوقتم."], ["How are you? — I'm fine, thanks.", "حالت چطوره؟ — خوبم، ممنون."], ["Where are you from? — I'm from Iran.", "اهل کجایی؟ — من اهل ایران هستم."], ["See you tomorrow!", "فردا می‌بینمت!"]] },
      { type: "rule", html: "برای معرفی خود: <code>My name is …</code> یا <code>I'm …</code><br>برای پرسیدن اسم: <code>What's your name?</code>" },
      { type: "tip", text: "در پاسخ به How are you? معمولاً می‌گوییم: I'm fine / I'm good / Not bad, thanks. And you?" },
    ],
    practice: [
      { q: "Nice to ___ you.", opts: ["meet", "make", "see", "do"], a: 0 },
      { q: "___ are you from?", opts: ["What", "Where", "Who", "How"], a: 1 },
      { q: "Good ___ (at 8 AM)", opts: ["night", "evening", "morning", "afternoon"], a: 2 },
    ],
  },
  {
    id: "a1-tobe", level: "A1", title: "فعل To Be", en: "Verb To Be (am / is / are)",
    summary: "مهم‌ترین فعل انگلیسی: هستم، هستی، هست",
    content: [
      { type: "p", text: "فعل To Be معادل «بودن» در فارسی است و بسته به فاعل، سه شکل دارد: am, is, are." },
      { type: "table", head: ["Subject", "To Be", "Contraction", "Example"], rows: [["I", "am", "I'm", "I am a student."], ["You", "are", "You're", "You are tall."], ["He / She / It", "is", "He's / She's / It's", "She is a doctor."], ["We", "are", "We're", "We are friends."], ["They", "are", "They're", "They are happy."]] },
      { type: "rule", html: "منفی: <code>am not / is not (isn't) / are not (aren't)</code><br>سوالی: فعل به اول جمله می‌آید → <code>Are you a teacher?</code>" },
      { type: "examples", items: [["I am from Tehran.", "من اهل تهران هستم."], ["She isn't at home.", "او خانه نیست."], ["Are they students? — Yes, they are.", "آیا آن‌ها دانش‌آموزند؟ — بله."], ["It is cold today.", "امروز هوا سرد است."]] },
      { type: "tip", text: "در پاسخ کوتاه، شکل مخفف استفاده نمی‌شود: Yes, I am. (نه Yes, I'm.)" },
    ],
    practice: [
      { q: "She ___ a nurse.", opts: ["am", "is", "are", "be"], a: 1 },
      { q: "They ___ from Canada.", opts: ["is", "am", "are", "be"], a: 2 },
      { q: "___ you tired?", opts: ["Am", "Is", "Are", "Be"], a: 2 },
      { q: "I ___ not hungry.", opts: ["am", "is", "are", "do"], a: 0 },
    ],
  },
  {
    id: "a1-articles", level: "A1", title: "حروف تعریف", en: "Articles: a / an / the",
    summary: "کاربرد a, an و the",
    content: [
      { type: "p", text: "حروف تعریف قبل از اسم می‌آیند. a/an برای اسم‌های نامعین و مفرد، و the برای اسم‌های معین (شناخته‌شده) به کار می‌رود." },
      { type: "rule", html: "<code>a</code> قبل از صدای بی‌صدا: a book, a car, a university<br><code>an</code> قبل از صدای صدادار: an apple, an hour, an umbrella<br><code>the</code> برای چیز مشخص: the sun, the book on the table" },
      { type: "examples", items: [["I have a dog. The dog is brown.", "من یک سگ دارم. آن سگ قهوه‌ای است."], ["She is an engineer.", "او مهندس است."], ["The moon is bright tonight.", "ماه امشب روشن است."], ["He waited for an hour.", "او یک ساعت منتظر ماند."]] },
      { type: "tip", text: "معیار، صداست نه حرف! «hour» با h نوشته می‌شود اما با صدای صدادار شروع می‌شود → an hour. «university» با u نوشته می‌شود اما صدای /j/ دارد → a university." },
    ],
    practice: [
      { q: "I saw ___ elephant.", opts: ["a", "an", "the", "—"], a: 1 },
      { q: "She has ___ car.", opts: ["a", "an", "—", "some"], a: 0 },
      { q: "___ sun rises in the east.", opts: ["A", "An", "The", "—"], a: 2 },
    ],
  },
  {
    id: "a1-numbers", level: "A1", title: "اعداد، زمان و تاریخ", en: "Numbers, Time & Dates",
    summary: "شمارش، گفتن ساعت، روزهای هفته و ماه‌ها",
    content: [
      { type: "table", head: ["Number", "Word", "Ordinal"], rows: [["1", "one", "first (1st)"], ["2", "two", "second (2nd)"], ["3", "three", "third (3rd)"], ["4", "four", "fourth (4th)"], ["5", "five", "fifth (5th)"], ["10", "ten", "tenth"], ["12", "twelve", "twelfth"], ["20", "twenty", "twentieth"], ["100", "one hundred", "hundredth"], ["1000", "one thousand", "thousandth"]] },
      { type: "rule", html: "ساعت: <code>It's 3 o'clock.</code> / <code>It's half past two (2:30).</code> / <code>It's quarter to five (4:45).</code><br>روزها: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday<br>ماه‌ها: January, February, March, April, May, June, July, August, September, October, November, December" },
      { type: "examples", items: [["What time is it? — It's ten past nine.", "ساعت چنده؟ — نه و ده دقیقه."], ["My birthday is on May 5th.", "تولد من پنجم مه است."], ["Today is Wednesday.", "امروز چهارشنبه است."], ["I have two brothers and one sister.", "من دو برادر و یک خواهر دارم."]] },
      { type: "tip", text: "برای روزها و تاریخ‌ها از on و برای ماه‌ها و سال‌ها از in استفاده کنید: on Monday, on July 4th — in March, in 2026." },
    ],
    practice: [
      { q: "4:30 → It's half ___ four.", opts: ["to", "past", "at", "of"], a: 1 },
      { q: "The ___ day of the week is Tuesday. (2nd)", opts: ["two", "twice", "second", "secondly"], a: 2 },
      { q: "I was born ___ 1995.", opts: ["on", "at", "in", "by"], a: 2 },
    ],
  },
  {
    id: "a1-present-simple", level: "A1", title: "حال ساده", en: "Present Simple",
    summary: "عادت‌ها، حقایق و کارهای روزمره",
    content: [
      { type: "p", text: "حال ساده برای بیان عادت‌ها، حقایق کلی و برنامه‌های ثابت استفاده می‌شود. برای سوم‌شخص مفرد (he/she/it) به فعل s یا es اضافه می‌کنیم." },
      { type: "table", head: ["Subject", "Positive", "Negative", "Question"], rows: [["I / You / We / They", "work", "don't work", "Do you work?"], ["He / She / It", "works", "doesn't work", "Does she work?"]] },
      { type: "rule", html: "قواعد افزودن s: <code>go → goes</code>, <code>watch → watches</code>, <code>study → studies</code>, <code>play → plays</code>, <code>have → has</code><br>قیدهای تکرار: always, usually, often, sometimes, rarely, never" },
      { type: "examples", items: [["I drink coffee every morning.", "من هر صبح قهوه می‌نوشم."], ["She works in a hospital.", "او در بیمارستان کار می‌کند."], ["Water boils at 100 degrees.", "آب در ۱۰۰ درجه می‌جوشد."], ["Do you like pizza? — Yes, I do.", "پیتزا دوست داری؟ — بله."], ["He doesn't play football.", "او فوتبال بازی نمی‌کند."]] },
    ],
    practice: [
      { q: "She ___ to school every day.", opts: ["go", "goes", "going", "gone"], a: 1 },
      { q: "___ they live in London?", opts: ["Does", "Is", "Do", "Are"], a: 2 },
      { q: "He ___ like tea.", opts: ["don't", "doesn't", "isn't", "not"], a: 1 },
      { q: "We usually ___ TV at night.", opts: ["watch", "watches", "watching", "watched"], a: 0 },
    ],
  },
  {
    id: "a1-plurals", level: "A1", title: "اسم‌های جمع و ضمایر", en: "Plurals & Pronouns",
    summary: "جمع بستن اسم‌ها و ضمایر فاعلی، مفعولی و ملکی",
    content: [
      { type: "rule", html: "جمع باقاعده: <code>book → books</code>, <code>box → boxes</code>, <code>baby → babies</code>, <code>leaf → leaves</code><br>جمع بی‌قاعده: <code>man → men</code>, <code>woman → women</code>, <code>child → children</code>, <code>foot → feet</code>, <code>tooth → teeth</code>, <code>mouse → mice</code>, <code>person → people</code>" },
      { type: "table", head: ["Subject", "Object", "Possessive Adj.", "Possessive Pron."], rows: [["I", "me", "my", "mine"], ["you", "you", "your", "yours"], ["he", "him", "his", "his"], ["she", "her", "her", "hers"], ["it", "it", "its", "—"], ["we", "us", "our", "ours"], ["they", "them", "their", "theirs"]] },
      { type: "examples", items: [["This is my book. It's mine.", "این کتاب من است. مال من است."], ["I saw them at the park.", "آن‌ها را در پارک دیدم."], ["The children are playing.", "بچه‌ها دارند بازی می‌کنند."], ["Give it to her.", "آن را به او بده."]] },
    ],
    practice: [
      { q: "The plural of 'child' is:", opts: ["childs", "childes", "children", "childrens"], a: 2 },
      { q: "This car is ___. (belongs to us)", opts: ["our", "ours", "us", "we"], a: 1 },
      { q: "I gave the book to ___. (he)", opts: ["he", "his", "him", "himself"], a: 2 },
    ],
  },
  {
    id: "a2-present-continuous", level: "A2", title: "حال استمراری", en: "Present Continuous",
    summary: "کارهایی که همین الان در حال انجام‌اند",
    content: [
      { type: "p", text: "حال استمراری برای کارهایی که اکنون یا در همین دوره در حال انجام است و نیز برای برنامه‌های قطعی آینده به کار می‌رود." },
      { type: "rule", html: "ساختار: <code>am / is / are + verb-ing</code><br>قواعد ing: <code>make → making</code>, <code>run → running</code>, <code>lie → lying</code><br>نشانه‌ها: now, right now, at the moment, currently, these days" },
      { type: "examples", items: [["I am studying English now.", "الان دارم انگلیسی می‌خوانم."], ["She is not sleeping.", "او نخوابیده است (در حال خوابیدن نیست)."], ["Are you listening to me?", "داری به من گوش می‌دی؟"], ["We're meeting Ali tomorrow.", "فردا با علی قرار داریم."]] },
      { type: "tip", text: "افعال حالتی (state verbs) معمولاً استمراری نمی‌شوند: know, like, love, want, need, believe, understand. ✗ I am knowing → ✓ I know." },
    ],
    practice: [
      { q: "Look! It ___ raining.", opts: ["is", "are", "am", "be"], a: 0 },
      { q: "They ___ football at the moment.", opts: ["play", "plays", "are playing", "played"], a: 2 },
      { q: "I ___ this song. (like)", opts: ["am liking", "like", "liking", "likes"], a: 1 },
    ],
  },
  {
    id: "a2-past-simple", level: "A2", title: "گذشتهٔ ساده", en: "Past Simple",
    summary: "کارهای تمام‌شده در گذشته",
    content: [
      { type: "p", text: "گذشتهٔ ساده برای اعمالی به کار می‌رود که در زمان مشخصی در گذشته اتفاق افتاده و تمام شده‌اند." },
      { type: "rule", html: "باقاعده: <code>verb + ed</code> → work → worked, play → played, stop → stopped, study → studied<br>منفی: <code>didn't + verb</code> — سوالی: <code>Did + subject + verb?</code><br>نشانه‌ها: yesterday, last week, ago, in 2010" },
      { type: "table", head: ["Base", "Past", "Past Participle", "فارسی"], rows: [["go", "went", "gone", "رفتن"], ["see", "saw", "seen", "دیدن"], ["eat", "ate", "eaten", "خوردن"], ["have", "had", "had", "داشتن"], ["make", "made", "made", "ساختن"], ["take", "took", "taken", "گرفتن"], ["come", "came", "come", "آمدن"], ["write", "wrote", "written", "نوشتن"], ["buy", "bought", "bought", "خریدن"], ["think", "thought", "thought", "فکر کردن"], ["get", "got", "gotten/got", "گرفتن/شدن"], ["know", "knew", "known", "دانستن"]] },
      { type: "examples", items: [["I visited my grandmother yesterday.", "دیروز به مادربزرگم سر زدم."], ["She didn't come to the party.", "او به مهمانی نیامد."], ["Did you see the movie? — No, I didn't.", "فیلم را دیدی؟ — نه."], ["They went to Shiraz last year.", "پارسال به شیراز رفتند."]] },
    ],
    practice: [
      { q: "I ___ a great book last week.", opts: ["read", "readed", "reading", "reads"], a: 0 },
      { q: "She ___ go to work yesterday.", opts: ["don't", "doesn't", "didn't", "wasn't"], a: 2 },
      { q: "___ you enjoy the trip?", opts: ["Do", "Did", "Were", "Have"], a: 1 },
      { q: "The past of 'buy' is:", opts: ["buyed", "bought", "buied", "brought"], a: 1 },
    ],
  },
  {
    id: "a2-future", level: "A2", title: "آینده", en: "Future: will & going to",
    summary: "تفاوت will و be going to",
    content: [
      { type: "table", head: ["Form", "Use", "Example"], rows: [["will + verb", "تصمیم لحظه‌ای، پیش‌بینی، قول", "I'll help you."], ["be going to + verb", "برنامهٔ از قبل، پیش‌بینی با شواهد", "I'm going to study medicine."], ["Present Continuous", "قرار قطعی", "We're flying to Paris on Friday."]] },
      { type: "examples", items: [["It will rain tomorrow.", "فردا باران خواهد بارید."], ["I'm going to buy a new phone.", "قصد دارم گوشی جدید بخرم."], ["Look at those clouds! It's going to rain.", "ابرها را ببین! باران می‌آید."], ["Don't worry, I won't tell anyone.", "نگران نباش، به کسی نمی‌گویم."]] },
      { type: "tip", text: "won't = will not. مخفف will در محاوره بسیار رایج است: I'll, you'll, she'll." },
    ],
    practice: [
      { q: "The phone is ringing. — I ___ answer it.", opts: ["will", "am going to", "going to", "would"], a: 0 },
      { q: "We ___ visit Italy next summer. (planned)", opts: ["will", "are going to", "go", "went"], a: 1 },
    ],
  },
  {
    id: "a2-comparatives", level: "A2", title: "صفات تفضیلی و عالی", en: "Comparatives & Superlatives",
    summary: "بزرگ‌تر، بزرگ‌ترین",
    content: [
      { type: "table", head: ["Adjective", "Comparative", "Superlative"], rows: [["tall", "taller", "the tallest"], ["big", "bigger", "the biggest"], ["happy", "happier", "the happiest"], ["beautiful", "more beautiful", "the most beautiful"], ["good", "better", "the best"], ["bad", "worse", "the worst"], ["far", "farther/further", "the farthest"]] },
      { type: "rule", html: "صفت کوتاه: <code>-er / the -est</code> — صفت بلند: <code>more / the most</code><br>برابری: <code>as … as</code> → She is as tall as her brother." },
      { type: "examples", items: [["Tehran is bigger than Isfahan.", "تهران از اصفهان بزرگ‌تر است."], ["This is the best restaurant in town.", "این بهترین رستوران شهر است."], ["English is easier than Chinese.", "انگلیسی آسان‌تر از چینی است."]] },
    ],
    practice: [
      { q: "My car is ___ than yours.", opts: ["fast", "faster", "fastest", "more fast"], a: 1 },
      { q: "She is the ___ student in class.", opts: ["intelligent", "more intelligent", "most intelligent", "intelligentest"], a: 2 },
      { q: "The comparative of 'good' is:", opts: ["gooder", "more good", "better", "best"], a: 2 },
    ],
  },
  {
    id: "a2-modals", level: "A2", title: "افعال کمکی وجهی", en: "Modal Verbs: can, must, should",
    summary: "توانایی، اجازه، اجبار و توصیه",
    content: [
      { type: "table", head: ["Modal", "Meaning", "Example"], rows: [["can / can't", "توانایی، اجازه", "I can swim."], ["could", "توانایی گذشته، درخواست مودبانه", "Could you help me?"], ["must / mustn't", "اجبار / ممنوعیت", "You must wear a seatbelt."], ["have to", "اجبار (بیرونی)", "I have to work on Sundays."], ["should / shouldn't", "توصیه", "You should see a doctor."], ["may / might", "احتمال", "It might snow tonight."]] },
      { type: "rule", html: "بعد از افعال وجهی همیشه شکل سادهٔ فعل می‌آید: <code>She can swims</code> ✗ → <code>She can swim</code> ✓" },
      { type: "examples", items: [["Can I open the window?", "می‌توانم پنجره را باز کنم؟"], ["You shouldn't eat so much sugar.", "نباید این‌قدر شکر بخوری."], ["We must finish this today.", "باید امروز این را تمام کنیم."]] },
    ],
    practice: [
      { q: "You ___ smoke here. It's forbidden.", opts: ["mustn't", "don't have to", "shouldn't", "can"], a: 0 },
      { q: "She ___ speak three languages.", opts: ["can to", "cans", "can", "is can"], a: 2 },
      { q: "I have a headache. — You ___ take a rest.", opts: ["should", "must to", "can't", "may not"], a: 0 },
    ],
  },
  {
    id: "a2-prepositions", level: "A2", title: "حروف اضافه", en: "Prepositions of Time & Place",
    summary: "in, on, at, under, between و ...",
    content: [
      { type: "table", head: ["Prep.", "Time", "Place"], rows: [["in", "in June, in 2020, in the morning", "in the room, in Tehran, in a box"], ["on", "on Monday, on May 1st, on the weekend", "on the table, on the wall, on the bus"], ["at", "at 5 o'clock, at night, at noon", "at home, at school, at the door"]] },
      { type: "rule", html: "مکان: <code>under</code> زیر، <code>behind</code> پشت، <code>in front of</code> جلوی، <code>next to</code> کنار، <code>between</code> بین، <code>above</code> بالای، <code>opposite</code> روبه‌روی" },
      { type: "examples", items: [["The cat is under the table.", "گربه زیر میز است."], ["I'll see you at 7 on Friday.", "جمعه ساعت ۷ می‌بینمت."], ["The bank is next to the post office.", "بانک کنار ادارهٔ پست است."]] },
    ],
    practice: [
      { q: "The meeting is ___ Monday.", opts: ["in", "on", "at", "by"], a: 1 },
      { q: "She lives ___ Paris.", opts: ["in", "on", "at", "to"], a: 0 },
      { q: "I wake up ___ 6 o'clock.", opts: ["in", "on", "at", "by"], a: 2 },
    ],
  },
  {
    id: "b1-present-perfect", level: "B1", title: "حال کامل", en: "Present Perfect",
    summary: "have / has + past participle",
    content: [
      { type: "p", text: "حال کامل پلی بین گذشته و حال است: تجربه‌های زندگی، اعمالی که تازه تمام شده‌اند یا اثرشان هنوز باقی است، و کارهایی که از گذشته تا حالا ادامه دارند." },
      { type: "rule", html: "ساختار: <code>have / has + past participle (V3)</code><br>نشانه‌ها: <code>ever, never, already, yet, just, since, for, so far</code>" },
      { type: "table", head: ["Present Perfect", "Past Simple"], rows: [["I have lived here for 5 years. (هنوز اینجا هستم)", "I lived there for 5 years. (دیگر آنجا نیستم)"], ["Have you ever been to Paris? (تجربه)", "Did you go to Paris last year? (زمان مشخص)"], ["She has just left. (همین الان)", "She left an hour ago. (زمان مشخص)"]] },
      { type: "examples", items: [["I have never eaten sushi.", "من هرگز سوشی نخورده‌ام."], ["Have you finished your homework yet?", "تکالیفت را تمام کرده‌ای؟"], ["She has worked here since 2019.", "او از ۲۰۱۹ اینجا کار می‌کند."], ["We've already seen that movie.", "ما قبلاً آن فیلم را دیده‌ایم."]] },
      { type: "tip", text: "since + نقطهٔ شروع (since Monday, since 2010) — for + مدت زمان (for two hours, for ten years)" },
    ],
    practice: [
      { q: "I ___ my keys. I can't find them.", opts: ["lost", "have lost", "lose", "am losing"], a: 1 },
      { q: "She has lived in Rome ___ 2015.", opts: ["for", "since", "from", "ago"], a: 1 },
      { q: "___ you ever ___ a famous person?", opts: ["Did / meet", "Have / met", "Do / meet", "Had / meet"], a: 1 },
      { q: "They ___ to Japan last year.", opts: ["have gone", "went", "have been", "go"], a: 1 },
    ],
  },
  {
    id: "b1-past-continuous", level: "B1", title: "گذشتهٔ استمراری", en: "Past Continuous",
    summary: "was / were + verb-ing",
    content: [
      { type: "rule", html: "ساختار: <code>was / were + verb-ing</code><br>کاربرد: عملی که در لحظه‌ای از گذشته در جریان بوده، معمولاً همراه با when / while" },
      { type: "examples", items: [["I was watching TV when the phone rang.", "داشتم تلویزیون می‌دیدم که تلفن زنگ زد."], ["While she was cooking, he was reading.", "وقتی او آشپزی می‌کرد، او (مرد) کتاب می‌خواند."], ["What were you doing at 9 last night?", "دیشب ساعت ۹ داشتی چه کار می‌کردی؟"]] },
      { type: "tip", text: "عمل طولانی → گذشتهٔ استمراری؛ عمل کوتاهی که آن را قطع می‌کند → گذشتهٔ ساده." },
    ],
    practice: [
      { q: "They ___ football when it started to rain.", opts: ["played", "were playing", "play", "have played"], a: 1 },
      { q: "While I ___, someone knocked on the door.", opts: ["slept", "sleep", "was sleeping", "have slept"], a: 2 },
    ],
  },
  {
    id: "b1-conditionals", level: "B1", title: "جملات شرطی نوع ۰، ۱ و ۲", en: "Conditionals 0, 1, 2",
    summary: "if + ...",
    content: [
      { type: "table", head: ["Type", "Structure", "Use", "Example"], rows: [["0", "If + present, present", "حقیقت کلی", "If you heat ice, it melts."], ["1", "If + present, will + verb", "شرط واقعی آینده", "If it rains, I will stay home."], ["2", "If + past, would + verb", "شرط غیرواقعی / خیالی", "If I were rich, I would travel the world."]] },
      { type: "examples", items: [["If you study hard, you will pass.", "اگر سخت درس بخوانی، قبول می‌شوی."], ["If I had more time, I would learn piano.", "اگر وقت بیشتری داشتم، پیانو یاد می‌گرفتم."], ["If I were you, I'd apologize.", "اگر جای تو بودم، عذرخواهی می‌کردم."]] },
      { type: "tip", text: "در شرطی نوع ۲، برای همهٔ فاعل‌ها می‌توان از were استفاده کرد: If I were / If she were." },
    ],
    practice: [
      { q: "If I ___ you, I would take the job.", opts: ["am", "was", "were", "be"], a: 2 },
      { q: "If it ___ tomorrow, we'll cancel the picnic.", opts: ["rains", "will rain", "rained", "rain"], a: 0 },
      { q: "If you mix red and blue, you ___ purple.", opts: ["will get", "get", "would get", "got"], a: 1 },
    ],
  },
  {
    id: "b1-question-tags", level: "B1", title: "سوالات ضمیمه و کلمات پرسشی", en: "Question Tags & Wh-Questions",
    summary: "isn't it? / don't you? / How long...?",
    content: [
      { type: "rule", html: "جملهٔ مثبت → تگ منفی: <code>You're a teacher, aren't you?</code><br>جملهٔ منفی → تگ مثبت: <code>She doesn't like it, does she?</code>" },
      { type: "table", head: ["Question Word", "Meaning", "Example"], rows: [["What", "چه", "What do you do?"], ["Where", "کجا", "Where do you live?"], ["When", "کی", "When is the exam?"], ["Why", "چرا", "Why are you late?"], ["Who", "چه کسی", "Who is that man?"], ["How", "چطور", "How do you go to work?"], ["How long", "چه مدت", "How long have you lived here?"], ["How often", "هر چند وقت", "How often do you exercise?"], ["Which", "کدام", "Which color do you prefer?"]] },
      { type: "examples", items: [["It's a beautiful day, isn't it?", "روز قشنگی است، نه؟"], ["You haven't seen my phone, have you?", "گوشی مرا ندیده‌ای، دیده‌ای؟"], ["How much does it cost?", "قیمتش چقدر است؟"]] },
    ],
    practice: [
      { q: "You like coffee, ___?", opts: ["do you", "don't you", "aren't you", "like you"], a: 1 },
      { q: "___ do you brush your teeth? — Twice a day.", opts: ["How long", "How often", "How much", "When"], a: 1 },
    ],
  },
  {
    id: "b1-gerund-inf", level: "B1", title: "مصدر و اسم مصدر", en: "Gerunds & Infinitives",
    summary: "enjoy doing / want to do",
    content: [
      { type: "table", head: ["+ verb-ing", "+ to verb", "both"], rows: [["enjoy, finish, mind, avoid, suggest, keep, practice", "want, decide, hope, plan, agree, learn, promise, need", "like, love, hate, start, begin, continue"]] },
      { type: "examples", items: [["I enjoy swimming.", "از شنا لذت می‌برم."], ["She decided to move to Canada.", "او تصمیم گرفت به کانادا مهاجرت کند."], ["Stop talking!", "حرف نزن!"], ["I forgot to lock the door. (فراموش کردم قفل کنم)", "Vs. I forgot locking the door. (یادم نیست قفل کردم)"]] },
      { type: "rule", html: "بعد از حروف اضافه همیشه <code>-ing</code>: interested in learning, good at cooking, before leaving" },
    ],
    practice: [
      { q: "I don't mind ___ the dishes.", opts: ["to wash", "washing", "wash", "washed"], a: 1 },
      { q: "They agreed ___ us.", opts: ["helping", "help", "to help", "helped"], a: 2 },
      { q: "She is good at ___.", opts: ["draw", "to draw", "drawing", "drew"], a: 2 },
    ],
  },
  {
    id: "b2-passive", level: "B2", title: "جملات مجهول", en: "Passive Voice",
    summary: "be + past participle",
    content: [
      { type: "p", text: "وقتی فاعل مهم یا مشخص نیست، یا می‌خواهیم روی عمل تأکید کنیم، از مجهول استفاده می‌کنیم." },
      { type: "table", head: ["Tense", "Active", "Passive"], rows: [["Present Simple", "They make cars here.", "Cars are made here."], ["Past Simple", "Someone stole my bike.", "My bike was stolen."], ["Present Perfect", "She has written a letter.", "A letter has been written."], ["Future", "They will build a bridge.", "A bridge will be built."], ["Modal", "You must finish it.", "It must be finished."]] },
      { type: "examples", items: [["This book was written by Hafez.", "این کتاب توسط حافظ نوشته شده است."], ["English is spoken all over the world.", "انگلیسی در سراسر دنیا صحبت می‌شود."], ["The room is being cleaned right now.", "اتاق همین الان دارد تمیز می‌شود."]] },
      { type: "tip", text: "فاعل را فقط زمانی با by ذکر کنید که مهم باشد." },
    ],
    practice: [
      { q: "The Mona Lisa ___ by Leonardo da Vinci.", opts: ["painted", "was painted", "is painting", "has painted"], a: 1 },
      { q: "Rice ___ in many Asian countries.", opts: ["grows", "is grown", "grown", "growing"], a: 1 },
      { q: "The results ___ tomorrow.", opts: ["will announce", "are announced", "will be announced", "announce"], a: 2 },
    ],
  },
  {
    id: "b2-reported", level: "B2", title: "نقل قول غیرمستقیم", en: "Reported Speech",
    summary: "He said (that) he was tired.",
    content: [
      { type: "table", head: ["Direct", "Reported"], rows: [["\"I am tired.\"", "She said (that) she was tired."], ["\"I will call you.\"", "He said he would call me."], ["\"I have finished.\"", "She said she had finished."], ["\"Do you like it?\"", "He asked if I liked it."], ["\"Where do you live?\"", "She asked where I lived."], ["\"Close the door.\"", "He told me to close the door."]] },
      { type: "rule", html: "تغییر زمان‌ها: present → past, past → past perfect, will → would, can → could<br>تغییر قیدها: now → then, today → that day, tomorrow → the next day, here → there" },
      { type: "examples", items: [["\"I'm learning English,\" she said. → She said she was learning English.", "او گفت که دارد انگلیسی یاد می‌گیرد."], ["He asked me if I could help him.", "او از من پرسید آیا می‌توانم کمکش کنم."]] },
    ],
    practice: [
      { q: "\"I love this city.\" → He said he ___ that city.", opts: ["loves", "loved", "had loved", "is loving"], a: 1 },
      { q: "\"Can you swim?\" → She asked me ___ swim.", opts: ["if I could", "can I", "if I can", "that I could"], a: 0 },
    ],
  },
  {
    id: "b2-past-perfect", level: "B2", title: "گذشتهٔ کامل و شرطی نوع ۳", en: "Past Perfect & Third Conditional",
    summary: "had + V3 / If I had known...",
    content: [
      { type: "rule", html: "گذشتهٔ کامل: <code>had + past participle</code> → عملی که قبل از عمل دیگری در گذشته اتفاق افتاده<br>شرطی نوع ۳: <code>If + had + V3, would have + V3</code> → حسرت / موقعیت غیرواقعی در گذشته" },
      { type: "examples", items: [["When I arrived, the train had already left.", "وقتی رسیدم، قطار قبلاً رفته بود."], ["She had never seen snow before she moved to Canada.", "او قبل از مهاجرت به کانادا هرگز برف ندیده بود."], ["If I had studied harder, I would have passed the exam.", "اگر بیشتر درس خوانده بودم، امتحان را قبول می‌شدم."], ["If you had told me, I would have helped.", "اگر به من گفته بودی، کمک می‌کردم."]] },
    ],
    practice: [
      { q: "By the time we got there, the movie ___.", opts: ["started", "has started", "had started", "starts"], a: 2 },
      { q: "If she ___ the bus, she wouldn't have been late.", opts: ["caught", "had caught", "has caught", "would catch"], a: 1 },
    ],
  },
  {
    id: "b2-relative", level: "B2", title: "جملات موصولی", en: "Relative Clauses",
    summary: "who, which, that, whose, where",
    content: [
      { type: "table", head: ["Pronoun", "Refers to", "Example"], rows: [["who", "people", "The man who called you is my boss."], ["which", "things / animals", "The book which I bought is great."], ["that", "people / things", "This is the car that I want."], ["whose", "possession", "That's the woman whose son is a pilot."], ["where", "places", "This is the café where we met."], ["when", "time", "I remember the day when we met."]] },
      { type: "rule", html: "جملهٔ موصولی <b>تعریفی</b> (بدون ویرگول): اطلاعات ضروری → The girl who lives next door is a doctor.<br>جملهٔ موصولی <b>غیرتعریفی</b> (با ویرگول): اطلاعات اضافی → My brother, who lives in Paris, is a chef." },
      { type: "examples", items: [["The phone that I bought yesterday is broken.", "گوشی‌ای که دیروز خریدم خراب است."], ["Tehran, which is the capital of Iran, is very crowded.", "تهران که پایتخت ایران است، بسیار شلوغ است."]] },
    ],
    practice: [
      { q: "The woman ___ lives next door is a lawyer.", opts: ["which", "who", "whose", "where"], a: 1 },
      { q: "That's the restaurant ___ we had dinner.", opts: ["which", "who", "where", "when"], a: 2 },
      { q: "He's the author ___ books I love.", opts: ["who", "which", "whose", "that"], a: 2 },
    ],
  },
  {
    id: "b2-phrasal", level: "B2", title: "افعال دوکلمه‌ای", en: "Phrasal Verbs",
    summary: "give up, look after, put off ...",
    content: [
      { type: "table", head: ["Phrasal Verb", "Meaning", "Example"], rows: [["give up", "ترک کردن، تسلیم شدن", "Don't give up!"], ["look after", "مراقبت کردن", "She looks after her little brother."], ["look for", "دنبال چیزی گشتن", "I'm looking for my keys."], ["put off", "به تعویق انداختن", "They put off the meeting."], ["turn on / off", "روشن / خاموش کردن", "Turn off the lights."], ["get up", "از خواب بلند شدن", "I get up at 7."], ["run out of", "تمام شدن", "We've run out of milk."], ["find out", "فهمیدن، کشف کردن", "I found out the truth."], ["carry on", "ادامه دادن", "Carry on with your work."], ["come across", "برخوردن به", "I came across an old photo."], ["bring up", "بزرگ کردن / مطرح کردن", "She brought up three kids."], ["figure out", "سر در آوردن", "I can't figure out this problem."]] },
      { type: "tip", text: "افعال دوکلمه‌ای جداشدنی: turn the light off / turn off the light — اما با ضمیر فقط: turn it off ✓ turn off it ✗" },
    ],
    practice: [
      { q: "We've ___ sugar. Can you buy some?", opts: ["run out of", "given up", "put off", "looked after"], a: 0 },
      { q: "Please ___ the TV. I'm studying.", opts: ["turn off", "turn up", "find out", "get up"], a: 0 },
      { q: "I couldn't ___ how to open the box.", opts: ["look after", "carry on", "figure out", "bring up"], a: 2 },
    ],
  },
  {
    id: "c1-inversion", level: "C1", title: "وارونگی و تأکید", en: "Inversion & Emphasis",
    summary: "Never have I seen... / Not only... but also",
    content: [
      { type: "p", text: "در سطح پیشرفته، برای تأکید یا سبک رسمی، ترتیب فاعل و فعل کمکی جابه‌جا می‌شود — به‌ویژه بعد از قیدهای منفی در ابتدای جمله." },
      { type: "rule", html: "<code>Never</code> have I seen such beauty.<br><code>Not only</code> did she win, <code>but</code> she <code>also</code> broke the record.<br><code>Rarely / Seldom</code> do we get such an opportunity.<br><code>Hardly</code> had I arrived <code>when</code> it started raining.<br><code>No sooner</code> had he left <code>than</code> the phone rang.<br><code>Only when</code> I got home did I realize my mistake.<br>Cleft sentences: <code>It was John who</code> broke the window. / <code>What I need is</code> a break." },
      { type: "examples", items: [["Under no circumstances should you open this door.", "تحت هیچ شرایطی نباید این در را باز کنید."], ["Little did they know what was coming.", "اصلاً نمی‌دانستند چه چیزی در راه است."], ["Had I known, I would have come earlier.", "اگر می‌دانستم، زودتر می‌آمدم."]] },
    ],
    practice: [
      { q: "Never ___ such a beautiful sunset.", opts: ["I have seen", "have I seen", "I saw", "did I seen"], a: 1 },
      { q: "Not only ___ late, but he also forgot the documents.", opts: ["he was", "was he", "he is", "is he"], a: 1 },
      { q: "___ had I sat down when the phone rang.", opts: ["Hardly", "Only", "Rarely", "Never"], a: 0 },
    ],
  },
  {
    id: "c1-idioms", level: "C1", title: "اصطلاحات رایج", en: "Common Idioms",
    summary: "break the ice, piece of cake ...",
    content: [
      { type: "table", head: ["Idiom", "Meaning", "Example"], rows: [["a piece of cake", "خیلی آسان", "The exam was a piece of cake."], ["break the ice", "سر صحبت را باز کردن", "He told a joke to break the ice."], ["hit the books", "سخت درس خواندن", "I need to hit the books tonight."], ["once in a blue moon", "خیلی به‌ندرت", "We eat out once in a blue moon."], ["under the weather", "ناخوش", "I'm feeling a bit under the weather."], ["cost an arm and a leg", "خیلی گران بودن", "That car cost an arm and a leg."], ["the ball is in your court", "نوبت توست تصمیم بگیری", "I've done my part; the ball is in your court."], ["beat around the bush", "طفره رفتن", "Stop beating around the bush!"], ["hit the nail on the head", "دقیقاً درست گفتن", "You hit the nail on the head."], ["let the cat out of the bag", "راز را لو دادن", "She let the cat out of the bag about the party."], ["burn the midnight oil", "تا دیروقت کار کردن", "I burned the midnight oil to finish."], ["get cold feet", "لحظهٔ آخر ترسیدن", "He got cold feet before the wedding."]] },
      { type: "tip", text: "اصطلاحات را کلمه‌به‌کلمه ترجمه نکنید! معنای کلی را حفظ کنید و در جمله به کار ببرید." },
    ],
    practice: [
      { q: "The test was so easy — it was a piece of ___.", opts: ["bread", "cake", "pie", "candy"], a: 1 },
      { q: "'Under the weather' means:", opts: ["outside", "sick", "happy", "cold"], a: 1 },
      { q: "Stop ___ around the bush and tell me!", opts: ["running", "walking", "beating", "hitting"], a: 2 },
    ],
  },
  {
    id: "c1-writing", level: "C1", title: "نگارش رسمی و ایمیل", en: "Formal Writing & Emails",
    summary: "ساختار ایمیل رسمی، کلمات ربط، لحن",
    content: [
      { type: "rule", html: "ساختار ایمیل رسمی:<br>1. <code>Dear Mr. / Ms. Smith,</code> یا <code>Dear Sir/Madam,</code><br>2. هدف: <code>I am writing to inquire about / to apply for / regarding …</code><br>3. بدنه با پاراگراف‌های کوتاه<br>4. پایان: <code>I look forward to hearing from you.</code><br>5. <code>Yours sincerely,</code> (نام مشخص) / <code>Yours faithfully,</code> (Dear Sir/Madam)" },
      { type: "table", head: ["Function", "Linking words"], rows: [["افزودن", "Furthermore, Moreover, In addition, Additionally"], ["تضاد", "However, Nevertheless, On the other hand, Whereas, Although"], ["نتیجه", "Therefore, Consequently, As a result, Thus"], ["مثال", "For instance, For example, such as, namely"], ["جمع‌بندی", "In conclusion, To sum up, Overall, All things considered"]] },
      { type: "table", head: ["Informal", "Formal"], rows: [["get", "obtain / receive"], ["ask", "inquire / request"], ["help", "assist"], ["need", "require"], ["a lot of", "a great deal of / numerous"], ["but", "however"], ["so", "therefore"], ["I think", "I believe / In my opinion"]] },
      { type: "examples", items: [["I am writing to express my interest in the position advertised on your website.", "این نامه را برای ابراز علاقه به موقعیت شغلی اعلام‌شده در وب‌سایت شما می‌نویسم."], ["Should you require any further information, please do not hesitate to contact me.", "در صورت نیاز به اطلاعات بیشتر، لطفاً با من تماس بگیرید."]] },
    ],
    practice: [
      { q: "Formal ending when you know the name:", opts: ["Yours faithfully", "Yours sincerely", "Cheers", "Bye"], a: 1 },
      { q: "A formal synonym for 'ask':", opts: ["inquire", "shout", "tell", "say"], a: 0 },
      { q: "Which word shows contrast?", opts: ["Moreover", "Therefore", "However", "Namely"], a: 2 },
    ],
  },
  {
    id: "c1-advanced-vocab", level: "C1", title: "واژگان پیشرفته و هم‌آیی‌ها", en: "Advanced Vocabulary & Collocations",
    summary: "make vs do, strong coffee, heavy rain",
    content: [
      { type: "p", text: "هم‌آیی (collocation) یعنی کلماتی که به‌طور طبیعی با هم می‌آیند. استفادهٔ درست از آن‌ها زبان شما را طبیعی و بومی‌تر می‌کند." },
      { type: "table", head: ["make", "do"], rows: [["make a decision / a mistake / money / friends / an effort / progress / a difference", "do homework / business / research / the dishes / your best / a favor / exercise"]] },
      { type: "table", head: ["Collocation", "✗ Wrong", "فارسی"], rows: [["heavy rain", "strong rain", "باران شدید"], ["strong coffee", "powerful coffee", "قهوهٔ غلیظ"], ["fast food", "quick food", "فست‌فود"], ["take a photo", "make a photo", "عکس گرفتن"], ["pay attention", "give attention", "توجه کردن"], ["catch a cold", "take a cold", "سرما خوردن"], ["highly recommended", "very recommended", "به‌شدت توصیه‌شده"], ["deeply concerned", "very concerned", "عمیقاً نگران"]] },
      { type: "examples", items: [["We need to make a decision by Friday.", "باید تا جمعه تصمیم بگیریم."], ["She's making great progress in English.", "او در انگلیسی پیشرفت زیادی می‌کند."], ["Could you do me a favor?", "می‌شود لطفی به من بکنی؟"]] },
    ],
    practice: [
      { q: "I need to ___ my homework.", opts: ["make", "do", "take", "have"], a: 1 },
      { q: "She ___ a big mistake.", opts: ["did", "took", "made", "had"], a: 2 },
      { q: "There was ___ rain last night.", opts: ["strong", "heavy", "big", "hard"], a: 1 },
    ],
  },
];

/* --- Vocabulary --- */
const VOCAB_CATEGORIES = { basics: "پایه", family: "خانواده", food: "غذا", travel: "سفر", work: "کار", body: "بدن و سلامت", home: "خانه", nature: "طبیعت", emotions: "احساسات", time: "زمان", verbs: "افعال", adjectives: "صفات", academic: "آکادمیک", business: "تجارت", tech: "فناوری" };

const VOCAB = [
  // basics A1
  ["hello", "/həˈloʊ/", "سلام", "Hello, how are you?", "basics", "A1"],
  ["goodbye", "/ɡʊdˈbaɪ/", "خداحافظ", "Goodbye, see you soon!", "basics", "A1"],
  ["please", "/pliːz/", "لطفاً", "Please sit down.", "basics", "A1"],
  ["thank you", "/θæŋk juː/", "متشکرم", "Thank you very much.", "basics", "A1"],
  ["sorry", "/ˈsɒri/", "ببخشید", "Sorry, I'm late.", "basics", "A1"],
  ["yes", "/jes/", "بله", "Yes, I agree.", "basics", "A1"],
  ["no", "/noʊ/", "نه", "No, thank you.", "basics", "A1"],
  ["water", "/ˈwɔːtər/", "آب", "Can I have some water?", "food", "A1"],
  ["bread", "/bred/", "نان", "I eat bread for breakfast.", "food", "A1"],
  ["apple", "/ˈæpəl/", "سیب", "An apple a day keeps the doctor away.", "food", "A1"],
  ["milk", "/mɪlk/", "شیر", "I drink milk every morning.", "food", "A1"],
  ["rice", "/raɪs/", "برنج", "Rice is popular in Iran.", "food", "A1"],
  ["tea", "/tiː/", "چای", "Would you like some tea?", "food", "A1"],
  ["coffee", "/ˈkɒfi/", "قهوه", "I need a cup of coffee.", "food", "A1"],
  ["egg", "/eɡ/", "تخم‌مرغ", "I had two eggs for breakfast.", "food", "A1"],
  ["chicken", "/ˈtʃɪkɪn/", "مرغ", "We had chicken for dinner.", "food", "A1"],
  ["fish", "/fɪʃ/", "ماهی", "Fish is healthy.", "food", "A1"],
  ["mother", "/ˈmʌðər/", "مادر", "My mother is a teacher.", "family", "A1"],
  ["father", "/ˈfɑːðər/", "پدر", "My father works in a bank.", "family", "A1"],
  ["brother", "/ˈbrʌðər/", "برادر", "I have one brother.", "family", "A1"],
  ["sister", "/ˈsɪstər/", "خواهر", "My sister is younger than me.", "family", "A1"],
  ["son", "/sʌn/", "پسر (فرزند)", "Their son is five years old.", "family", "A1"],
  ["daughter", "/ˈdɔːtər/", "دختر (فرزند)", "She has two daughters.", "family", "A1"],
  ["husband", "/ˈhʌzbənd/", "شوهر", "Her husband is a doctor.", "family", "A1"],
  ["wife", "/waɪf/", "همسر (زن)", "His wife is from Shiraz.", "family", "A1"],
  ["grandmother", "/ˈɡrænmʌðər/", "مادربزرگ", "My grandmother tells great stories.", "family", "A1"],
  ["friend", "/frend/", "دوست", "She is my best friend.", "family", "A1"],
  ["house", "/haʊs/", "خانه", "We live in a small house.", "home", "A1"],
  ["room", "/ruːm/", "اتاق", "My room is upstairs.", "home", "A1"],
  ["kitchen", "/ˈkɪtʃɪn/", "آشپزخانه", "She is in the kitchen.", "home", "A1"],
  ["door", "/dɔːr/", "در", "Please close the door.", "home", "A1"],
  ["window", "/ˈwɪndoʊ/", "پنجره", "Open the window, please.", "home", "A1"],
  ["table", "/ˈteɪbəl/", "میز", "The book is on the table.", "home", "A1"],
  ["chair", "/tʃer/", "صندلی", "Sit on this chair.", "home", "A1"],
  ["bed", "/bed/", "تخت‌خواب", "I go to bed at 11.", "home", "A1"],
  ["car", "/kɑːr/", "ماشین", "He drives a red car.", "travel", "A1"],
  ["bus", "/bʌs/", "اتوبوس", "I take the bus to work.", "travel", "A1"],
  ["train", "/treɪn/", "قطار", "The train leaves at 9.", "travel", "A1"],
  ["airport", "/ˈerpɔːrt/", "فرودگاه", "We arrived at the airport early.", "travel", "A1"],
  ["ticket", "/ˈtɪkɪt/", "بلیت", "I bought two tickets.", "travel", "A1"],
  ["hotel", "/hoʊˈtel/", "هتل", "The hotel is near the beach.", "travel", "A1"],
  ["street", "/striːt/", "خیابان", "The shop is on this street.", "travel", "A1"],
  ["city", "/ˈsɪti/", "شهر", "Tehran is a big city.", "travel", "A1"],
  ["day", "/deɪ/", "روز", "Have a nice day!", "time", "A1"],
  ["night", "/naɪt/", "شب", "Good night!", "time", "A1"],
  ["morning", "/ˈmɔːrnɪŋ/", "صبح", "I run every morning.", "time", "A1"],
  ["week", "/wiːk/", "هفته", "See you next week.", "time", "A1"],
  ["month", "/mʌnθ/", "ماه", "I'll travel next month.", "time", "A1"],
  ["year", "/jɪr/", "سال", "Happy New Year!", "time", "A1"],
  ["today", "/təˈdeɪ/", "امروز", "Today is Monday.", "time", "A1"],
  ["tomorrow", "/təˈmɒroʊ/", "فردا", "See you tomorrow.", "time", "A1"],
  ["yesterday", "/ˈjestərdeɪ/", "دیروز", "I was busy yesterday.", "time", "A1"],
  ["head", "/hed/", "سر", "My head hurts.", "body", "A1"],
  ["hand", "/hænd/", "دست", "Wash your hands.", "body", "A1"],
  ["eye", "/aɪ/", "چشم", "She has blue eyes.", "body", "A1"],
  ["foot", "/fʊt/", "پا", "My foot is sore.", "body", "A1"],
  ["heart", "/hɑːrt/", "قلب", "Exercise is good for your heart.", "body", "A1"],
  ["big", "/bɪɡ/", "بزرگ", "It's a big house.", "adjectives", "A1"],
  ["small", "/smɔːl/", "کوچک", "A small cat.", "adjectives", "A1"],
  ["good", "/ɡʊd/", "خوب", "That's a good idea.", "adjectives", "A1"],
  ["bad", "/bæd/", "بد", "The weather is bad.", "adjectives", "A1"],
  ["hot", "/hɒt/", "داغ / گرم", "The tea is hot.", "adjectives", "A1"],
  ["cold", "/koʊld/", "سرد", "It's cold outside.", "adjectives", "A1"],
  ["new", "/nuː/", "جدید", "I bought a new phone.", "adjectives", "A1"],
  ["old", "/oʊld/", "قدیمی / پیر", "This is an old book.", "adjectives", "A1"],
  ["happy", "/ˈhæpi/", "خوشحال", "I'm so happy today!", "emotions", "A1"],
  ["sad", "/sæd/", "غمگین", "Why are you sad?", "emotions", "A1"],
  ["tired", "/ˈtaɪərd/", "خسته", "I'm tired after work.", "emotions", "A1"],
  ["hungry", "/ˈhʌŋɡri/", "گرسنه", "I'm hungry. Let's eat.", "emotions", "A1"],
  ["eat", "/iːt/", "خوردن", "Let's eat lunch.", "verbs", "A1"],
  ["drink", "/drɪŋk/", "نوشیدن", "Drink more water.", "verbs", "A1"],
  ["go", "/ɡoʊ/", "رفتن", "I go to school by bus.", "verbs", "A1"],
  ["come", "/kʌm/", "آمدن", "Come here, please.", "verbs", "A1"],
  ["see", "/siː/", "دیدن", "I see a bird.", "verbs", "A1"],
  ["like", "/laɪk/", "دوست داشتن", "I like music.", "verbs", "A1"],
  ["want", "/wɒnt/", "خواستن", "I want a new bag.", "verbs", "A1"],
  ["have", "/hæv/", "داشتن", "I have a question.", "verbs", "A1"],
  ["make", "/meɪk/", "ساختن / درست کردن", "She makes great cakes.", "verbs", "A1"],
  ["read", "/riːd/", "خواندن", "I read every night.", "verbs", "A1"],
  ["write", "/raɪt/", "نوشتن", "Write your name here.", "verbs", "A1"],
  ["speak", "/spiːk/", "صحبت کردن", "Do you speak English?", "verbs", "A1"],
  ["sun", "/sʌn/", "خورشید", "The sun is shining.", "nature", "A1"],
  ["tree", "/triː/", "درخت", "There's a tall tree in the garden.", "nature", "A1"],
  ["flower", "/ˈflaʊər/", "گل", "She loves flowers.", "nature", "A1"],
  ["rain", "/reɪn/", "باران", "I love the rain.", "nature", "A1"],
  ["dog", "/dɒɡ/", "سگ", "The dog is friendly.", "nature", "A1"],
  ["cat", "/kæt/", "گربه", "The cat is sleeping.", "nature", "A1"],
  ["bird", "/bɜːrd/", "پرنده", "Birds fly south in winter.", "nature", "A1"],
  ["job", "/dʒɒb/", "شغل", "I have a new job.", "work", "A1"],
  ["teacher", "/ˈtiːtʃər/", "معلم", "My teacher is kind.", "work", "A1"],
  ["doctor", "/ˈdɒktər/", "پزشک", "I need to see a doctor.", "work", "A1"],
  ["student", "/ˈstuːdənt/", "دانش‌آموز / دانشجو", "I'm a student.", "work", "A1"],
  ["money", "/ˈmʌni/", "پول", "I don't have any money.", "work", "A1"],
  ["phone", "/foʊn/", "تلفن", "Where's my phone?", "tech", "A1"],
  ["computer", "/kəmˈpjuːtər/", "کامپیوتر", "I work on a computer.", "tech", "A1"],
  // A2
  ["breakfast", "/ˈbrekfəst/", "صبحانه", "What do you have for breakfast?", "food", "A2"],
  ["vegetable", "/ˈvedʒtəbəl/", "سبزیجات", "Eat more vegetables.", "food", "A2"],
  ["delicious", "/dɪˈlɪʃəs/", "خوشمزه", "This soup is delicious!", "food", "A2"],
  ["restaurant", "/ˈrestrɒnt/", "رستوران", "Let's go to a restaurant.", "food", "A2"],
  ["menu", "/ˈmenjuː/", "منو", "Can I see the menu?", "food", "A2"],
  ["bill", "/bɪl/", "صورت‌حساب", "Can we have the bill, please?", "food", "A2"],
  ["cousin", "/ˈkʌzən/", "پسرعمو / دخترخاله و ...", "My cousin lives in Canada.", "family", "A2"],
  ["neighbor", "/ˈneɪbər/", "همسایه", "Our neighbors are very nice.", "family", "A2"],
  ["passport", "/ˈpæspɔːrt/", "گذرنامه", "Don't forget your passport.", "travel", "A2"],
  ["luggage", "/ˈlʌɡɪdʒ/", "چمدان / بار", "How much luggage do you have?", "travel", "A2"],
  ["journey", "/ˈdʒɜːrni/", "سفر", "It was a long journey.", "travel", "A2"],
  ["map", "/mæp/", "نقشه", "I need a map of the city.", "travel", "A2"],
  ["direction", "/dəˈrekʃən/", "جهت / مسیر", "Can you give me directions?", "travel", "A2"],
  ["abroad", "/əˈbrɔːd/", "خارج از کشور", "She studies abroad.", "travel", "A2"],
  ["office", "/ˈɒfɪs/", "دفتر / اداره", "I'm at the office.", "work", "A2"],
  ["meeting", "/ˈmiːtɪŋ/", "جلسه", "We have a meeting at 10.", "work", "A2"],
  ["salary", "/ˈsæləri/", "حقوق", "She earns a good salary.", "work", "A2"],
  ["boss", "/bɒs/", "رئیس", "My boss is very strict.", "work", "A2"],
  ["engineer", "/ˌendʒɪˈnɪr/", "مهندس", "He's a software engineer.", "work", "A2"],
  ["nurse", "/nɜːrs/", "پرستار", "The nurse was very kind.", "work", "A2"],
  ["headache", "/ˈhedeɪk/", "سردرد", "I have a terrible headache.", "body", "A2"],
  ["medicine", "/ˈmedɪsɪn/", "دارو", "Take this medicine twice a day.", "body", "A2"],
  ["healthy", "/ˈhelθi/", "سالم", "Eating fruit is healthy.", "body", "A2"],
  ["sick", "/sɪk/", "بیمار", "I feel sick.", "body", "A2"],
  ["exercise", "/ˈeksərsaɪz/", "ورزش", "I exercise every day.", "body", "A2"],
  ["furniture", "/ˈfɜːrnɪtʃər/", "مبلمان", "We bought new furniture.", "home", "A2"],
  ["garden", "/ˈɡɑːrdən/", "باغ / حیاط", "The kids play in the garden.", "home", "A2"],
  ["bathroom", "/ˈbæθruːm/", "حمام / دستشویی", "Where is the bathroom?", "home", "A2"],
  ["weather", "/ˈweðər/", "آب‌وهوا", "The weather is lovely today.", "nature", "A2"],
  ["mountain", "/ˈmaʊntən/", "کوه", "We climbed the mountain.", "nature", "A2"],
  ["river", "/ˈrɪvər/", "رودخانه", "The river is very wide.", "nature", "A2"],
  ["forest", "/ˈfɔːrɪst/", "جنگل", "We walked through the forest.", "nature", "A2"],
  ["beach", "/biːtʃ/", "ساحل", "Let's go to the beach.", "nature", "A2"],
  ["angry", "/ˈæŋɡri/", "عصبانی", "Don't be angry with me.", "emotions", "A2"],
  ["afraid", "/əˈfreɪd/", "ترسیده", "I'm afraid of spiders.", "emotions", "A2"],
  ["excited", "/ɪkˈsaɪtɪd/", "هیجان‌زده", "I'm excited about the trip.", "emotions", "A2"],
  ["bored", "/bɔːrd/", "بی‌حوصله", "I'm bored. Let's do something.", "emotions", "A2"],
  ["worried", "/ˈwɜːrid/", "نگران", "She's worried about the exam.", "emotions", "A2"],
  ["surprised", "/sərˈpraɪzd/", "متعجب", "I was surprised to see him.", "emotions", "A2"],
  ["arrive", "/əˈraɪv/", "رسیدن", "We arrived at noon.", "verbs", "A2"],
  ["leave", "/liːv/", "ترک کردن / رفتن", "I leave home at 8.", "verbs", "A2"],
  ["buy", "/baɪ/", "خریدن", "I want to buy a gift.", "verbs", "A2"],
  ["sell", "/sel/", "فروختن", "They sell fresh fruit.", "verbs", "A2"],
  ["forget", "/fərˈɡet/", "فراموش کردن", "Don't forget your keys.", "verbs", "A2"],
  ["remember", "/rɪˈmembər/", "به یاد آوردن", "I remember his name.", "verbs", "A2"],
  ["understand", "/ˌʌndərˈstænd/", "فهمیدن", "I don't understand.", "verbs", "A2"],
  ["travel", "/ˈtrævəl/", "سفر کردن", "I love to travel.", "verbs", "A2"],
  ["cook", "/kʊk/", "آشپزی کردن", "My dad cooks dinner.", "verbs", "A2"],
  ["clean", "/kliːn/", "تمیز کردن", "I clean my room on Fridays.", "verbs", "A2"],
  ["wait", "/weɪt/", "منتظر ماندن", "Please wait here.", "verbs", "A2"],
  ["cheap", "/tʃiːp/", "ارزان", "This shirt is cheap.", "adjectives", "A2"],
  ["expensive", "/ɪkˈspensɪv/", "گران", "That car is too expensive.", "adjectives", "A2"],
  ["beautiful", "/ˈbjuːtɪfəl/", "زیبا", "What a beautiful view!", "adjectives", "A2"],
  ["dangerous", "/ˈdeɪndʒərəs/", "خطرناک", "Driving fast is dangerous.", "adjectives", "A2"],
  ["famous", "/ˈfeɪməs/", "معروف", "He's a famous actor.", "adjectives", "A2"],
  ["difficult", "/ˈdɪfɪkəlt/", "دشوار", "This exercise is difficult.", "adjectives", "A2"],
  ["easy", "/ˈiːzi/", "آسان", "The test was easy.", "adjectives", "A2"],
  ["busy", "/ˈbɪzi/", "مشغول / شلوغ", "I'm busy right now.", "adjectives", "A2"],
  ["internet", "/ˈɪntərnet/", "اینترنت", "The internet is slow today.", "tech", "A2"],
  ["password", "/ˈpæswɜːrd/", "رمز عبور", "I forgot my password.", "tech", "A2"],
  ["email", "/ˈiːmeɪl/", "ایمیل", "Send me an email.", "tech", "A2"],
  ["download", "/ˌdaʊnˈloʊd/", "دانلود کردن", "Download the app.", "tech", "A2"],
  ["century", "/ˈsentʃəri/", "قرن", "We live in the 21st century.", "time", "A2"],
  ["weekend", "/ˌwiːkˈend/", "آخر هفته", "What are you doing this weekend?", "time", "A2"],
  // B1
  ["achieve", "/əˈtʃiːv/", "دست یافتن", "She achieved her goals.", "verbs", "B1"],
  ["improve", "/ɪmˈpruːv/", "بهبود بخشیدن", "I want to improve my English.", "verbs", "B1"],
  ["suggest", "/səˈdʒest/", "پیشنهاد دادن", "I suggest we leave early.", "verbs", "B1"],
  ["complain", "/kəmˈpleɪn/", "شکایت کردن", "He always complains about work.", "verbs", "B1"],
  ["avoid", "/əˈvɔɪd/", "اجتناب کردن", "Avoid junk food.", "verbs", "B1"],
  ["encourage", "/ɪnˈkɜːrɪdʒ/", "تشویق کردن", "Teachers should encourage students.", "verbs", "B1"],
  ["realize", "/ˈriːəlaɪz/", "متوجه شدن", "I realized my mistake.", "verbs", "B1"],
  ["recommend", "/ˌrekəˈmend/", "توصیه کردن", "Can you recommend a good book?", "verbs", "B1"],
  ["apply", "/əˈplaɪ/", "درخواست دادن", "I applied for the job.", "work", "B1"],
  ["interview", "/ˈɪntərvjuː/", "مصاحبه", "I have a job interview tomorrow.", "work", "B1"],
  ["experience", "/ɪkˈspɪriəns/", "تجربه", "She has five years of experience.", "work", "B1"],
  ["colleague", "/ˈkɒliːɡ/", "همکار", "My colleagues are friendly.", "work", "B1"],
  ["deadline", "/ˈdedlaɪn/", "مهلت", "The deadline is Friday.", "work", "B1"],
  ["promotion", "/prəˈmoʊʃən/", "ترفیع", "He got a promotion.", "work", "B1"],
  ["responsible", "/rɪˈspɒnsəbəl/", "مسئول", "You're responsible for this project.", "adjectives", "B1"],
  ["reliable", "/rɪˈlaɪəbəl/", "قابل اعتماد", "She's a reliable friend.", "adjectives", "B1"],
  ["confident", "/ˈkɒnfɪdənt/", "بااعتمادبه‌نفس", "Be confident in the interview.", "adjectives", "B1"],
  ["generous", "/ˈdʒenərəs/", "سخاوتمند", "He's very generous with his time.", "adjectives", "B1"],
  ["patient", "/ˈpeɪʃənt/", "صبور", "Be patient; it takes time.", "adjectives", "B1"],
  ["ambitious", "/æmˈbɪʃəs/", "جاه‌طلب", "She's an ambitious young lawyer.", "adjectives", "B1"],
  ["disappointed", "/ˌdɪsəˈpɔɪntɪd/", "ناامید / دلسرد", "I was disappointed with the result.", "emotions", "B1"],
  ["embarrassed", "/ɪmˈbærəst/", "خجالت‌زده", "I felt so embarrassed.", "emotions", "B1"],
  ["jealous", "/ˈdʒeləs/", "حسود", "He's jealous of his brother.", "emotions", "B1"],
  ["grateful", "/ˈɡreɪtfəl/", "سپاسگزار", "I'm grateful for your help.", "emotions", "B1"],
  ["anxious", "/ˈæŋkʃəs/", "مضطرب", "She feels anxious before exams.", "emotions", "B1"],
  ["environment", "/ɪnˈvaɪrənmənt/", "محیط زیست", "We must protect the environment.", "nature", "B1"],
  ["pollution", "/pəˈluːʃən/", "آلودگی", "Air pollution is a big problem.", "nature", "B1"],
  ["climate", "/ˈklaɪmət/", "اقلیم", "Climate change is real.", "nature", "B1"],
  ["recycle", "/ˌriːˈsaɪkəl/", "بازیافت کردن", "We recycle paper and plastic.", "nature", "B1"],
  ["injury", "/ˈɪndʒəri/", "آسیب / جراحت", "He suffered a serious injury.", "body", "B1"],
  ["symptom", "/ˈsɪmptəm/", "علامت بیماری", "Fever is a symptom of flu.", "body", "B1"],
  ["appointment", "/əˈpɔɪntmənt/", "قرار ملاقات / نوبت", "I have a dentist appointment.", "body", "B1"],
  ["prescription", "/prɪˈskrɪpʃən/", "نسخه", "The doctor gave me a prescription.", "body", "B1"],
  ["destination", "/ˌdestɪˈneɪʃən/", "مقصد", "What's your final destination?", "travel", "B1"],
  ["reservation", "/ˌrezərˈveɪʃən/", "رزرو", "I have a reservation for two.", "travel", "B1"],
  ["sightseeing", "/ˈsaɪtsiːɪŋ/", "گردش و بازدید", "We went sightseeing in Rome.", "travel", "B1"],
  ["accommodation", "/əˌkɒməˈdeɪʃən/", "محل اقامت", "The accommodation was excellent.", "travel", "B1"],
  ["device", "/dɪˈvaɪs/", "دستگاه", "Turn off all electronic devices.", "tech", "B1"],
  ["software", "/ˈsɔːftwer/", "نرم‌افزار", "Update your software.", "tech", "B1"],
  ["screen", "/skriːn/", "صفحه نمایش", "My phone screen is cracked.", "tech", "B1"],
  ["social media", "/ˌsoʊʃəl ˈmiːdiə/", "شبکه‌های اجتماعی", "She spends hours on social media.", "tech", "B1"],
  ["relationship", "/rɪˈleɪʃənʃɪp/", "رابطه", "They have a strong relationship.", "family", "B1"],
  ["argument", "/ˈɑːrɡjumənt/", "بحث / مشاجره", "We had an argument.", "family", "B1"],
  ["ingredient", "/ɪnˈɡriːdiənt/", "مادهٔ اولیه", "Mix all the ingredients.", "food", "B1"],
  ["recipe", "/ˈresəpi/", "دستور پخت", "Can I have the recipe?", "food", "B1"],
  ["although", "/ɔːlˈðoʊ/", "اگرچه", "Although it was raining, we went out.", "basics", "B1"],
  ["however", "/haʊˈevər/", "با این حال", "It's expensive. However, it's worth it.", "basics", "B1"],
  ["therefore", "/ˈðerfɔːr/", "بنابراین", "He was late; therefore, he missed the bus.", "basics", "B1"],
  ["decade", "/ˈdekeɪd/", "دهه", "A lot has changed in the last decade.", "time", "B1"],
  // B2
  ["accomplish", "/əˈkʌmplɪʃ/", "به انجام رساندن", "We accomplished a lot today.", "verbs", "B2"],
  ["persuade", "/pərˈsweɪd/", "متقاعد کردن", "She persuaded me to join.", "verbs", "B2"],
  ["negotiate", "/nɪˈɡoʊʃieɪt/", "مذاکره کردن", "We negotiated a better price.", "business", "B2"],
  ["overcome", "/ˌoʊvərˈkʌm/", "غلبه کردن", "He overcame his fear.", "verbs", "B2"],
  ["emphasize", "/ˈemfəsaɪz/", "تأکید کردن", "I must emphasize this point.", "verbs", "B2"],
  ["anticipate", "/ænˈtɪsɪpeɪt/", "پیش‌بینی کردن", "We anticipate a rise in prices.", "verbs", "B2"],
  ["undertake", "/ˌʌndərˈteɪk/", "بر عهده گرفتن", "She undertook a major project.", "verbs", "B2"],
  ["contribute", "/kənˈtrɪbjuːt/", "مشارکت کردن", "Everyone contributed to the success.", "verbs", "B2"],
  ["revenue", "/ˈrevənuː/", "درآمد", "Company revenue increased by 10%.", "business", "B2"],
  ["profit", "/ˈprɒfɪt/", "سود", "They made a huge profit.", "business", "B2"],
  ["investment", "/ɪnˈvestmənt/", "سرمایه‌گذاری", "It's a good long-term investment.", "business", "B2"],
  ["budget", "/ˈbʌdʒɪt/", "بودجه", "We're over budget.", "business", "B2"],
  ["customer", "/ˈkʌstəmər/", "مشتری", "The customer is always right.", "business", "B2"],
  ["competitor", "/kəmˈpetɪtər/", "رقیب", "Our main competitor is cheaper.", "business", "B2"],
  ["strategy", "/ˈstrætədʒi/", "راهبرد", "We need a new marketing strategy.", "business", "B2"],
  ["entrepreneur", "/ˌɒntrəprəˈnɜːr/", "کارآفرین", "She's a successful entrepreneur.", "business", "B2"],
  ["analyze", "/ˈænəlaɪz/", "تحلیل کردن", "Let's analyze the data.", "academic", "B2"],
  ["evidence", "/ˈevɪdəns/", "شواهد", "There is no evidence for this claim.", "academic", "B2"],
  ["hypothesis", "/haɪˈpɒθəsɪs/", "فرضیه", "The results support our hypothesis.", "academic", "B2"],
  ["significant", "/sɪɡˈnɪfɪkənt/", "قابل توجه", "There was a significant improvement.", "academic", "B2"],
  ["approach", "/əˈproʊtʃ/", "رویکرد", "We need a different approach.", "academic", "B2"],
  ["concept", "/ˈkɒnsept/", "مفهوم", "It's a difficult concept to grasp.", "academic", "B2"],
  ["theory", "/ˈθɪəri/", "نظریه", "Einstein's theory of relativity.", "academic", "B2"],
  ["controversial", "/ˌkɒntrəˈvɜːrʃəl/", "بحث‌برانگیز", "It's a controversial topic.", "adjectives", "B2"],
  ["inevitable", "/ɪnˈevɪtəbəl/", "اجتناب‌ناپذیر", "Change is inevitable.", "adjectives", "B2"],
  ["sophisticated", "/səˈfɪstɪkeɪtɪd/", "پیچیده / پیشرفته", "It's a sophisticated system.", "adjectives", "B2"],
  ["genuine", "/ˈdʒenjuɪn/", "اصیل / واقعی", "It's a genuine leather bag.", "adjectives", "B2"],
  ["reluctant", "/rɪˈlʌktənt/", "بی‌میل", "He was reluctant to help.", "adjectives", "B2"],
  ["overwhelmed", "/ˌoʊvərˈwelmd/", "غرق شده (در احساس)", "I feel overwhelmed with work.", "emotions", "B2"],
  ["frustrated", "/ˈfrʌstreɪtɪd/", "کلافه", "I'm frustrated with this app.", "emotions", "B2"],
  ["relieved", "/rɪˈliːvd/", "آسوده‌خاطر", "I was relieved to hear the news.", "emotions", "B2"],
  ["artificial intelligence", "/ˌɑːrtɪfɪʃəl ɪnˈtelɪdʒəns/", "هوش مصنوعی", "AI is changing the world.", "tech", "B2"],
  ["cybersecurity", "/ˌsaɪbərsɪˈkjʊrəti/", "امنیت سایبری", "Cybersecurity is a top priority.", "tech", "B2"],
  ["innovation", "/ˌɪnəˈveɪʃən/", "نوآوری", "Innovation drives growth.", "tech", "B2"],
  ["sustainable", "/səˈsteɪnəbəl/", "پایدار", "We need sustainable energy.", "nature", "B2"],
  ["biodiversity", "/ˌbaɪoʊdaɪˈvɜːrsəti/", "تنوع زیستی", "Forests protect biodiversity.", "nature", "B2"],
  ["nevertheless", "/ˌnevərðəˈles/", "با وجود این", "It was hard; nevertheless, we succeeded.", "basics", "B2"],
  ["whereas", "/werˈæz/", "در حالی که", "He's tall, whereas his brother is short.", "basics", "B2"],
  ["furthermore", "/ˌfɜːrðərˈmɔːr/", "علاوه بر این", "Furthermore, it's cheaper.", "basics", "B2"],
  // C1
  ["ubiquitous", "/juːˈbɪkwɪtəs/", "همه‌جا حاضر", "Smartphones are ubiquitous.", "academic", "C1"],
  ["meticulous", "/məˈtɪkjələs/", "بسیار دقیق", "She's meticulous about details.", "adjectives", "C1"],
  ["ambiguous", "/æmˈbɪɡjuəs/", "مبهم", "The message was ambiguous.", "adjectives", "C1"],
  ["pragmatic", "/præɡˈmætɪk/", "عمل‌گرا", "We need a pragmatic solution.", "adjectives", "C1"],
  ["eloquent", "/ˈeləkwənt/", "شیوا / خوش‌بیان", "She gave an eloquent speech.", "adjectives", "C1"],
  ["resilient", "/rɪˈzɪliənt/", "تاب‌آور", "Children are remarkably resilient.", "adjectives", "C1"],
  ["indispensable", "/ˌɪndɪˈspensəbəl/", "ضروری", "She's indispensable to the team.", "adjectives", "C1"],
  ["scrutinize", "/ˈskruːtənaɪz/", "موشکافی کردن", "The report was scrutinized carefully.", "verbs", "C1"],
  ["mitigate", "/ˈmɪtɪɡeɪt/", "کاهش دادن (اثر منفی)", "Measures to mitigate the risk.", "verbs", "C1"],
  ["advocate", "/ˈædvəkeɪt/", "حمایت کردن / طرفداری کردن", "She advocates for human rights.", "verbs", "C1"],
  ["exacerbate", "/ɪɡˈzæsərbeɪt/", "بدتر کردن", "Stress can exacerbate the illness.", "verbs", "C1"],
  ["alleviate", "/əˈliːvieɪt/", "تسکین دادن", "This drug alleviates pain.", "verbs", "C1"],
  ["substantiate", "/səbˈstænʃieɪt/", "اثبات کردن با شواهد", "Can you substantiate this claim?", "academic", "C1"],
  ["paradigm", "/ˈpærədaɪm/", "الگو / پارادایم", "A paradigm shift in science.", "academic", "C1"],
  ["nuance", "/ˈnuːɑːns/", "ظرافت معنایی", "The translation lost some nuance.", "academic", "C1"],
  ["discrepancy", "/dɪsˈkrepənsi/", "مغایرت", "There's a discrepancy in the figures.", "academic", "C1"],
  ["consensus", "/kənˈsensəs/", "اجماع", "We reached a consensus.", "academic", "C1"],
  ["empirical", "/ɪmˈpɪrɪkəl/", "تجربی", "Empirical evidence is required.", "academic", "C1"],
  ["intrinsic", "/ɪnˈtrɪnsɪk/", "ذاتی", "The intrinsic value of art.", "academic", "C1"],
  ["leverage", "/ˈlevərɪdʒ/", "اهرم / بهره‌گیری", "We can leverage our network.", "business", "C1"],
  ["stakeholder", "/ˈsteɪkhoʊldər/", "ذی‌نفع", "Consult all stakeholders.", "business", "C1"],
  ["acquisition", "/ˌækwɪˈzɪʃən/", "خرید / تملک شرکت", "The acquisition was worth $2 billion.", "business", "C1"],
  ["scalable", "/ˈskeɪləbəl/", "مقیاس‌پذیر", "The solution must be scalable.", "tech", "C1"],
  ["algorithm", "/ˈælɡərɪðəm/", "الگوریتم", "The algorithm sorts the data.", "tech", "C1"],
  ["melancholy", "/ˈmelənkɒli/", "اندوه / مالیخولیا", "A feeling of melancholy.", "emotions", "C1"],
  ["euphoric", "/juːˈfɔːrɪk/", "سرمست / شادمان", "The fans were euphoric.", "emotions", "C1"],
  ["apprehensive", "/ˌæprɪˈhensɪv/", "دلواپس", "I'm apprehensive about the results.", "emotions", "C1"],
  ["notwithstanding", "/ˌnɒtwɪθˈstændɪŋ/", "با وجود", "Notwithstanding the risks, we proceeded.", "basics", "C1"],
  ["albeit", "/ɔːlˈbiːɪt/", "هرچند", "He accepted, albeit reluctantly.", "basics", "C1"],
  ["hitherto", "/ˌhɪðərˈtuː/", "تاکنون", "A hitherto unknown species.", "basics", "C1"],
].map(([en, ph, fa, ex, cat, level]) => ({ en, ph, fa, ex, cat, level }));

/* --- Quiz questions (beyond lesson practice) --- */
const QUIZ = [
  // A1
  { level: "A1", q: "What is the opposite of 'hot'?", opts: ["warm", "cold", "big", "new"], a: 1, ex: "hot ↔ cold (داغ ↔ سرد)" },
  { level: "A1", q: "I ___ a student.", opts: ["is", "are", "am", "be"], a: 2, ex: "با I همیشه am می‌آید." },
  { level: "A1", q: "'Thank you' → correct reply:", opts: ["Please", "You're welcome", "Sorry", "Hello"], a: 1, ex: "پاسخ تشکر: You're welcome." },
  { level: "A1", q: "___ apple", opts: ["a", "an", "the a", "—"], a: 1, ex: "قبل از صدای صدادار an می‌آید." },
  { level: "A1", q: "She ___ TV every night.", opts: ["watch", "watches", "watching", "watched"], a: 1, ex: "سوم‌شخص مفرد: watch + es" },
  { level: "A1", q: "Which is a color?", opts: ["table", "blue", "run", "happy"], a: 1, ex: "blue = آبی" },
  { level: "A1", q: "'مادر' in English:", opts: ["father", "sister", "mother", "brother"], a: 2, ex: "mother = مادر" },
  { level: "A1", q: "Plural of 'man':", opts: ["mans", "men", "mens", "manes"], a: 1, ex: "جمع بی‌قاعده: man → men" },
  { level: "A1", q: "What time is 7:15?", opts: ["quarter to seven", "half past seven", "quarter past seven", "seven to quarter"], a: 2, ex: "7:15 = quarter past seven" },
  { level: "A1", q: "This is ___ book. (belongs to me)", opts: ["I", "me", "my", "mine"], a: 2, ex: "صفت ملکی قبل از اسم: my book" },
  { level: "A1", q: "___ they happy?", opts: ["Is", "Are", "Am", "Do"], a: 1, ex: "they + are" },
  { level: "A1", q: "'Goodbye' means:", opts: ["سلام", "خداحافظ", "ممنون", "لطفاً"], a: 1, ex: "" },
  { level: "A1", q: "Where ___ you from?", opts: ["is", "am", "are", "do"], a: 2, ex: "you + are" },
  { level: "A1", q: "I don't ___ coffee.", opts: ["likes", "like", "liking", "liked"], a: 1, ex: "بعد از don't شکل سادهٔ فعل" },
  { level: "A1", q: "The day after Monday is:", opts: ["Sunday", "Wednesday", "Tuesday", "Friday"], a: 2, ex: "Monday → Tuesday" },
  // A2
  { level: "A2", q: "Look! The baby ___.", opts: ["cries", "is crying", "cry", "cried"], a: 1, ex: "Look! نشانهٔ حال استمراری" },
  { level: "A2", q: "I ___ to Paris in 2019.", opts: ["go", "have gone", "went", "was going"], a: 2, ex: "زمان مشخص گذشته → گذشتهٔ ساده" },
  { level: "A2", q: "She is ___ than her sister.", opts: ["tall", "taller", "tallest", "more tall"], a: 1, ex: "صفت کوتاه + er" },
  { level: "A2", q: "You ___ drive without a license.", opts: ["mustn't", "don't have to", "should", "might"], a: 0, ex: "ممنوعیت: mustn't" },
  { level: "A2", q: "The meeting is ___ 3 o'clock.", opts: ["in", "on", "at", "by"], a: 2, ex: "ساعت دقیق: at" },
  { level: "A2", q: "I think it ___ rain tomorrow.", opts: ["is", "will", "going to", "does"], a: 1, ex: "پیش‌بینی بدون شواهد: will" },
  { level: "A2", q: "'Expensive' means:", opts: ["ارزان", "گران", "زیبا", "بزرگ"], a: 1, ex: "" },
  { level: "A2", q: "Past of 'go':", opts: ["goed", "gone", "went", "going"], a: 2, ex: "go → went → gone" },
  { level: "A2", q: "This is the ___ movie I've ever seen.", opts: ["good", "better", "best", "most good"], a: 2, ex: "صفت عالی good → the best" },
  { level: "A2", q: "___ you swim when you were five?", opts: ["Can", "Could", "Do", "Are"], a: 1, ex: "توانایی در گذشته: could" },
  { level: "A2", q: "The keys are ___ the table.", opts: ["in", "on", "at", "to"], a: 1, ex: "روی سطح: on" },
  { level: "A2", q: "We ___ dinner when he called.", opts: ["had", "were having", "have", "are having"], a: 1, ex: "عمل در جریان در گذشته" },
  { level: "A2", q: "I'm ___ about my exam.", opts: ["worry", "worried", "worrying", "worries"], a: 1, ex: "worried about = نگران" },
  { level: "A2", q: "She ___ like spicy food.", opts: ["don't", "doesn't", "isn't", "not"], a: 1, ex: "سوم‌شخص مفرد منفی: doesn't" },
  { level: "A2", q: "'Cheap' is the opposite of:", opts: ["big", "old", "expensive", "easy"], a: 2, ex: "" },
  // B1
  { level: "B1", q: "I ___ here since 2020.", opts: ["live", "lived", "have lived", "am living"], a: 2, ex: "since + حال کامل" },
  { level: "B1", q: "If I ___ rich, I'd buy a boat.", opts: ["am", "was", "were", "will be"], a: 2, ex: "شرطی نوع ۲: If I were" },
  { level: "B1", q: "She enjoys ___ novels.", opts: ["read", "to read", "reading", "reads"], a: 2, ex: "enjoy + ing" },
  { level: "B1", q: "He's a doctor, ___?", opts: ["is he", "isn't he", "doesn't he", "does he"], a: 1, ex: "جملهٔ مثبت → تگ منفی" },
  { level: "B1", q: "Have you ___ been to London?", opts: ["never", "ever", "yet", "already"], a: 1, ex: "ever در سوالات تجربه" },
  { level: "B1", q: "I ___ lunch when the fire alarm rang.", opts: ["ate", "was eating", "have eaten", "eat"], a: 1, ex: "گذشتهٔ استمراری برای عمل در جریان" },
  { level: "B1", q: "'Improve' means:", opts: ["بدتر شدن", "بهبود یافتن", "شکایت کردن", "خریدن"], a: 1, ex: "" },
  { level: "B1", q: "She decided ___ a new car.", opts: ["buying", "buy", "to buy", "bought"], a: 2, ex: "decide + to + verb" },
  { level: "B1", q: "How ___ have you been waiting?", opts: ["often", "long", "much", "far"], a: 1, ex: "How long = چه مدت" },
  { level: "B1", q: "I've known her ___ ten years.", opts: ["since", "for", "from", "during"], a: 1, ex: "for + مدت زمان" },
  { level: "B1", q: "If you heat water to 100°C, it ___.", opts: ["boils", "will boil", "would boil", "boiled"], a: 0, ex: "شرطی نوع صفر: حقیقت علمی" },
  { level: "B1", q: "I'm interested ___ learning Spanish.", opts: ["on", "at", "in", "for"], a: 2, ex: "interested in + ing" },
  { level: "B1", q: "She's ___ just left the office.", opts: ["—", "has", "have", "had"], a: 0, ex: "She's = She has (قبلاً has آمده)" },
  { level: "B1", q: "'Reliable' means:", opts: ["تنبل", "قابل اعتماد", "عصبانی", "گران"], a: 1, ex: "" },
  { level: "B1", q: "We ___ finished yet.", opts: ["don't", "haven't", "didn't", "aren't"], a: 1, ex: "yet + حال کامل منفی" },
  // B2
  { level: "B2", q: "The bridge ___ in 1932.", opts: ["built", "was built", "is built", "has built"], a: 1, ex: "مجهول گذشته: was/were + V3" },
  { level: "B2", q: "She said she ___ tired.", opts: ["is", "was", "has been", "be"], a: 1, ex: "نقل قول: present → past" },
  { level: "B2", q: "When I arrived, they ___ already ___.", opts: ["have / left", "had / left", "were / left", "did / leave"], a: 1, ex: "گذشتهٔ کامل برای عمل قبلی" },
  { level: "B2", q: "The man ___ car was stolen called the police.", opts: ["who", "which", "whose", "that"], a: 2, ex: "مالکیت: whose" },
  { level: "B2", q: "We've ___ milk.", opts: ["run out of", "given up", "put off", "carried on"], a: 0, ex: "run out of = تمام شدن" },
  { level: "B2", q: "If I had known, I ___ you.", opts: ["would tell", "would have told", "will tell", "told"], a: 1, ex: "شرطی نوع ۳" },
  { level: "B2", q: "'Reluctant' means:", opts: ["مشتاق", "بی‌میل", "خوشحال", "سریع"], a: 1, ex: "" },
  { level: "B2", q: "He asked me where ___.", opts: ["do I live", "I lived", "did I live", "I live"], a: 1, ex: "سوال غیرمستقیم: ترتیب جملهٔ خبری + past" },
  { level: "B2", q: "This letter must ___ today.", opts: ["send", "be sent", "sent", "be send"], a: 1, ex: "مجهول با modal: must be + V3" },
  { level: "B2", q: "The company's ___ rose by 20%.", opts: ["revenue", "colleague", "symptom", "luggage"], a: 0, ex: "revenue = درآمد" },
  { level: "B2", q: "Don't ___ until tomorrow what you can do today.", opts: ["put off", "look after", "turn on", "find out"], a: 0, ex: "put off = به تعویق انداختن" },
  { level: "B2", q: "My sister, ___ lives in Rome, is visiting us.", opts: ["that", "who", "which", "whose"], a: 1, ex: "غیرتعریفی: who (نه that)" },
  { level: "B2", q: "\"I'll call you tomorrow.\" → He said he ___ me the next day.", opts: ["will call", "would call", "called", "calls"], a: 1, ex: "will → would" },
  { level: "B2", q: "'Inevitable' means:", opts: ["ممکن", "اجتناب‌ناپذیر", "نادر", "آسان"], a: 1, ex: "" },
  { level: "B2", q: "I wish I ___ more time.", opts: ["have", "had", "will have", "having"], a: 1, ex: "wish + past simple برای حال" },
  // C1
  { level: "C1", q: "Never ___ such a mess.", opts: ["I saw", "have I seen", "I have seen", "did I saw"], a: 1, ex: "وارونگی بعد از Never" },
  { level: "C1", q: "The exam was a piece of ___.", opts: ["bread", "pie", "cake", "sugar"], a: 2, ex: "a piece of cake = خیلی آسان" },
  { level: "C1", q: "'Ubiquitous' means:", opts: ["نادر", "همه‌جا حاضر", "گران", "قدیمی"], a: 1, ex: "" },
  { level: "C1", q: "Only after the meeting ___ the problem.", opts: ["I understood", "did I understand", "I did understand", "understood I"], a: 1, ex: "Only after … + وارونگی" },
  { level: "C1", q: "Formal synonym for 'get':", opts: ["grab", "obtain", "take", "catch"], a: 1, ex: "obtain = رسمی" },
  { level: "C1", q: "Measures were taken to ___ the damage.", opts: ["exacerbate", "mitigate", "advocate", "scrutinize"], a: 1, ex: "mitigate = کاهش دادن" },
  { level: "C1", q: "___ the bad weather, the match went ahead.", opts: ["Although", "Despite", "However", "Because"], a: 1, ex: "Despite + اسم" },
  { level: "C1", q: "He ___ the midnight oil to finish the report.", opts: ["burned", "hit", "broke", "let"], a: 0, ex: "burn the midnight oil" },
  { level: "C1", q: "We need to ___ a decision.", opts: ["do", "make", "take up", "have"], a: 1, ex: "make a decision" },
  { level: "C1", q: "Which is a cleft sentence?", opts: ["I need a break.", "It was John who broke it.", "John broke it.", "Did John break it?"], a: 1, ex: "It was X who … = cleft" },
  { level: "C1", q: "'Meticulous' means:", opts: ["بی‌دقت", "بسیار دقیق", "سریع", "خسته"], a: 1, ex: "" },
  { level: "C1", q: "No sooner had I arrived ___ it started to rain.", opts: ["when", "than", "then", "that"], a: 1, ex: "No sooner … than" },
  { level: "C1", q: "'The ball is in your court' means:", opts: ["Let's play tennis", "It's your decision now", "You lost", "You're late"], a: 1, ex: "" },
  { level: "C1", q: "Had I known, I ___ earlier.", opts: ["would come", "would have come", "came", "had come"], a: 1, ex: "شرطی نوع ۳ با وارونگی" },
  { level: "C1", q: "Formal letter ending when you don't know the name:", opts: ["Yours sincerely", "Yours faithfully", "Best", "Love"], a: 1, ex: "Dear Sir/Madam → Yours faithfully" },
];

/* --- Speaking sentences --- */
const SPEAK_SENTENCES = [
  ["Hello, my name is Ali. Nice to meet you.", "سلام، اسم من علی است. از آشنایی‌تان خوشوقتم."],
  ["Could you tell me where the train station is?", "می‌توانید بگویید ایستگاه قطار کجاست؟"],
  ["I would like a cup of coffee, please.", "لطفاً یک فنجان قهوه می‌خواهم."],
  ["What time does the museum open?", "موزه چه ساعتی باز می‌شود؟"],
  ["I have been learning English for two years.", "دو سال است که دارم انگلیسی یاد می‌گیرم."],
  ["The weather is beautiful today, isn't it?", "امروز هوا عالی است، نه؟"],
  ["Can I have the bill, please?", "می‌شود صورت‌حساب را بیاورید؟"],
  ["I'm sorry, I didn't understand. Could you repeat that?", "ببخشید، متوجه نشدم. می‌شود تکرار کنید؟"],
  ["How much does this cost?", "قیمت این چقدر است؟"],
  ["I usually wake up at seven o'clock.", "معمولاً ساعت هفت بیدار می‌شوم."],
  ["She has already finished her homework.", "او قبلاً تکالیفش را تمام کرده است."],
  ["If it rains tomorrow, we will stay at home.", "اگر فردا باران ببارد، خانه می‌مانیم."],
  ["The thirty-three thieves thought that they thrilled the throne.", "(تمرین صدای th)"],
  ["She sells seashells by the seashore.", "(تمرین s و sh)"],
  ["I'd like to book a room for two nights.", "می‌خواهم یک اتاق برای دو شب رزرو کنم."],
];

/* --- Dialogs --- */
const DIALOGS = [
  { title: "☕ در کافه", lines: [["Waiter: Good morning! What can I get you?", "صبح بخیر! چه چیزی برایتان بیاورم؟"], ["Customer: I'd like a cappuccino and a croissant, please.", "یک کاپوچینو و یک کروسان لطفاً."], ["Waiter: Anything else?", "چیز دیگری؟"], ["Customer: No, that's all. How much is it?", "نه، همین. چقدر می‌شود؟"], ["Waiter: That'll be six dollars.", "شش دلار می‌شود."]] },
  { title: "🏨 در هتل", lines: [["Guest: Hi, I have a reservation under the name Rezaei.", "سلام، به نام رضایی رزرو دارم."], ["Receptionist: Let me check… Yes, a double room for three nights.", "بگذارید بررسی کنم… بله، اتاق دونفره برای سه شب."], ["Guest: Great. What time is breakfast?", "عالی. صبحانه چه ساعتی است؟"], ["Receptionist: From 7 to 10 in the dining hall. Here's your key.", "از ۷ تا ۱۰ در سالن غذاخوری. این هم کلیدتان."]] },
  { title: "🗺️ پرسیدن آدرس", lines: [["A: Excuse me, how do I get to the post office?", "ببخشید، چطور به ادارهٔ پست بروم؟"], ["B: Go straight ahead, then turn left at the traffic lights.", "مستقیم بروید، بعد سر چراغ راهنما بپیچید چپ."], ["A: Is it far from here?", "از اینجا دور است؟"], ["B: No, it's about a five-minute walk.", "نه، حدود پنج دقیقه پیاده است."]] },
  { title: "🩺 نزد پزشک", lines: [["Doctor: What seems to be the problem?", "مشکل چیست؟"], ["Patient: I've had a sore throat and a fever since yesterday.", "از دیروز گلودرد و تب دارم."], ["Doctor: Let me have a look. It looks like a mild infection.", "بگذارید ببینم. به نظر عفونت خفیف است."], ["Patient: Do I need antibiotics?", "به آنتی‌بیوتیک نیاز دارم؟"], ["Doctor: No, just rest and drink plenty of fluids.", "نه، فقط استراحت کنید و مایعات زیاد بنوشید."]] },
  { title: "💼 مصاحبهٔ شغلی", lines: [["Interviewer: Tell me a little about yourself.", "کمی از خودتان بگویید."], ["Candidate: I'm a software developer with five years of experience.", "من توسعه‌دهندهٔ نرم‌افزار با پنج سال سابقه هستم."], ["Interviewer: Why do you want to work here?", "چرا می‌خواهید اینجا کار کنید؟"], ["Candidate: I admire your company's focus on innovation.", "تمرکز شرکت شما روی نوآوری را تحسین می‌کنم."], ["Interviewer: What are your strengths?", "نقاط قوت شما چیست؟"], ["Candidate: I'm a fast learner and I work well under pressure.", "سریع یاد می‌گیرم و زیر فشار خوب کار می‌کنم."]] },
  { title: "🛍️ خرید لباس", lines: [["Customer: Excuse me, do you have this shirt in medium?", "ببخشید، این پیراهن را سایز مدیوم دارید؟"], ["Assistant: Let me check… Yes, here you go.", "بگذارید ببینم… بله، بفرمایید."], ["Customer: Can I try it on?", "می‌توانم امتحانش کنم؟"], ["Assistant: Of course, the fitting rooms are over there.", "البته، اتاق پرو آن‌طرف است."], ["Customer: It fits perfectly. I'll take it.", "کاملاً اندازه است. می‌برمش."]] },
  { title: "📞 تماس تلفنی", lines: [["A: Hello, could I speak to Mr. Karimi, please?", "الو، می‌توانم با آقای کریمی صحبت کنم؟"], ["B: I'm afraid he's in a meeting. Can I take a message?", "متأسفانه در جلسه هستند. پیامی دارید؟"], ["A: Yes, please ask him to call me back. My number is 555-1234.", "بله، لطفاً بگویید با من تماس بگیرند. شماره‌ام ۵۵۵-۱۲۳۴ است."], ["B: Sure, I'll let him know.", "حتماً، به ایشان اطلاع می‌دهم."]] },
];

/* --- Badges --- */
const BADGES = [
  { id: "first-lesson", icon: "🌱", name: "اولین قدم", desc: "اولین درس را تمام کنید", check: (s) => s.lessons.length >= 1 },
  { id: "five-lessons", icon: "📚", name: "کتاب‌خوان", desc: "۵ درس کامل کنید", check: (s) => s.lessons.length >= 5 },
  { id: "all-a1", icon: "🥉", name: "فارغ‌التحصیل A1", desc: "همهٔ درس‌های A1", check: (s) => LESSONS.filter((l) => l.level === "A1").every((l) => s.lessons.includes(l.id)) },
  { id: "all-lessons", icon: "🏆", name: "استاد", desc: "همهٔ درس‌ها را تمام کنید", check: (s) => LESSONS.every((l) => s.lessons.includes(l.id)) },
  { id: "words-25", icon: "🔤", name: "واژه‌باز", desc: "۲۵ واژه یاد بگیرید", check: (s) => s.words.length >= 25 },
  { id: "words-100", icon: "📖", name: "لغت‌نامه", desc: "۱۰۰ واژه یاد بگیرید", check: (s) => s.words.length >= 100 },
  { id: "quiz-1", icon: "📝", name: "آزمون‌دهنده", desc: "اولین آزمون", check: (s) => s.quizzes >= 1 },
  { id: "quiz-perfect", icon: "💯", name: "بی‌نقص", desc: "نمرهٔ کامل در یک آزمون", check: (s) => s.perfect >= 1 },
  { id: "streak-3", icon: "🔥", name: "شعله", desc: "۳ روز استریک", check: (s) => s.bestStreak >= 3 },
  { id: "streak-7", icon: "⚡", name: "یک هفته", desc: "۷ روز استریک", check: (s) => s.bestStreak >= 7 },
  { id: "xp-500", icon: "⭐", name: "ستاره", desc: "۵۰۰ XP", check: (s) => s.xp >= 500 },
  { id: "xp-2000", icon: "🌟", name: "ابرستاره", desc: "۲۰۰۰ XP", check: (s) => s.xp >= 2000 },
];
